[phases.build]
cmds = ["npm ci --production --prefer-offline", "npm cache clean --force"]
nixpkgsArchive = "https://github.com/NixOS/nixpkgs/archive/nixos-23.11.tar.gz"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/npm-cache"
NODE_VERSION = "22"

[start]
cmd = "node index.js"
